### ISSUE TITLE
Add warning when code didn't save because of bad yaml

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/researcher-portal#15]
Right now, when save is clicked, we try to parse what's in the code editor.  If an error is thrown, nothing happens.  We want to add some sort of pop up so that users know that their work wasn't saved and they have a mistake somewhere.

We may also want to add the option to revert to the most recent save of their file.

**Comment by JamesPHoughton** [comment]
depends on validators, start with a dummy template.
