### ISSUE TITLE
Make elements/stages clickable to edit

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/researcher-portal#25]
**As a user, I want to click on element or stage cards to edit them**

Successful completion of this issue involves

- [ ] build functionality of an edit window - this probably has similar functionality as the add popup
- [ ] being able to click on an element card to edit it
- [ ] being able to click on a stage card to edit it
- [ ] all changes are propagated in the code editor yaml
- [ ] nothing breaks

**Comment by JamesPHoughton** [comment]
@evanping @christabusho - is this still relevant?
