### ISSUE TITLE
Use drag and drop for reordering of elements and stages

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/researcher-portal#3]
**As a user, I want to drag and drop elements and stages to reorder them.**

This issue may require finding a drag and drop library for completion. Successful completion of this issue requires:

- [x] Finding a good drag and drop library if needed
- [x] Ability to drag and drop stages to reorder
- [x] Ability to drag and drop elements to reorder
- [x] Code editor yaml is updated
- [x] Nothing breaks
- [x] Add new Cypress tests for drap and drop. See example from deliberation-empirica here: https://github.com/Watts-Lab/deliberation-empirica/blob/10a82582dc9f251743d644b391900aa50617df83/cypress/e2e/01_Normal_Paths_Omnibus.js#L622

**Comment by JamesPHoughton** [comment]
in deliberation-empirica, we're already using: https://github.com/hello-pangea/dnd, may as well use the same library
