### ISSUE TITLE
Implement ability to render actual elements

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/researcher-portal#30]
As a user I want to see what elements will look like on a participant's interface.

This can probably be copied from deliberation-empirica.  We know it will be used in the render panel but may want to be used in the Timeline as well for users to preview each element individually.  

The challenge here will be to fetch the appropriate files for the prompt especially.

**Comment by JamesPHoughton** [comment]
todos:
- add additional components
- mock stage timer
- use windii CSS from deliberation-empirica in render window
