### ISSUE TITLE
Figure out how to reuse zod types for form inputs

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/researcher-portal#44]
As a developer, I want to use existing types for different objects when possible, to save the work (and potential mistakes) of redefining them.

We are using zod to create validators for the treatment syntax (still in progress). We can use zod to convert these to types to use in the various forms.

**Comment by christabusho** [comment]
We adjusted the zod schemas that were created in the deliberation-empirica repo to satisfy the properties needed for both the validation for the forms and in empirica. We also added schemas needed only in the form so we can import them in the addPopup file (by adding the empirica repo as a submodule) and use them as part of updating the addPopup using the react hook form

**Comment by JamesPHoughton** [comment]
Just need to merge changes and test

**Comment by JamesPHoughton** [comment]
issue with bringing teh submodule up to date, ready to review pr

**Comment by JamesPHoughton** [comment]
https://github.com/Watts-Lab/deliberation-empirica/pull/865/files
