### ISSUE TITLE
Error highlighting for yaml editor window

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/researcher-portal#47]
As a researcher, i want to easily spot issues with my `x.treatments.yaml` file, so that I can fix them without getting frustrated.

One way to do this would be with validation that uses red/yellow underline squiggles to indicate problems. There may be a way to do this automatically, or to get the information we need to do it from the zod validator for the treatments. This probably needs to wait until we have that validator written.

**Comment by JamesPHoughton** [comment]
This might be an interesting plugin for monaco: https://microsoft.github.io/monaco-editor/monarch.html

**Comment by shapeseas** [comment]
Working version so far. Deals with errors in YAML structure and errors as defined by Zod schema for treatments.
![treatment_code_editor](https://github.com/user-attachments/assets/fd02cb61-d08d-41cf-addf-ab50abbfa010)
