### ISSUE TITLE
[FEATURE]: Default/Sample YAML Treatment

### ISSUE THREAD

**Issue by evanping** [Watts-Lab/researcher-portal#54]
### User Story

As a researcher using the researcher portal, I want to see a default yaml treatment upon loading the researcher portal so that not only are all the interactive elements loaded, I have something more intuitive to build upon.

### Feature description

Add a default yaml treatment to the code editor. Can have name, description, players, and empty gamestages list.

### What would this feature enable?

Allows the add stage button to show up because with an empty code editor the bottom left section is empty. Also gives the user a foundation to build their experiment off of.

### Priority

None

**Comment by JamesPHoughton** [comment]
This could be pulled either from the examples in the `deliberation-empirica` test suite, or from the example in `deliberation-assets`. Feel free to edit either of those as you see fit to make it a good example/default for this case.

**Comment by evanping** [comment]
Existing setup treatment done

**Comment by evanping** [comment]
May have to update the default treatment in the future as changes are made.
