### ISSUE TITLE
[Bug]: Surveys don't render in the render panel

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/researcher-portal#61]
### What happened?

When a survey is used, it should fetch the appropriate survey and render it in the render panel. At the moment, it throws an error.

### What browsers do you see the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What operating system do you see the problem on?

- [ ] Windows
- [X] Mac
- [ ] Linux

### How did we discover the bug?

- [ ] Reported by participant
- [ ] Observed on Sentry
- [X] Found in dev

### Priority

Blocking some use

**Comment by evanping** [comment]
Should be fixed, surveyName was an open ended input and is a dropdown now
